config/routes.rb
Rails.application.routes.draw do

  authenticate :user do

    namespace :employer do
      get 'dashboard/coders'
      get 'dashboard/profile/:user_id' => 'dashboard#profile', as: :student_profile
    end

    namespace :student do
      get 'dashboard/home'
      get 'dashboard/performance'
      get 'dashboard/tracks'
      get 'dashboard/resources'
      get 'tracks/:id' => 'tracks#show', as: :tracks
    end

    namespace :teacher do
      get 'dashboard' => redirect('teacher/dashboard/grades/filters')
      get 'dashboard/grades' => redirect('teacher/dashboard/grades/filters')
      get 'dashboard/class_stats'
      get 'dashboard/student_status'
      get 'dashboard/teacher_stats'
      get 'dashboard/grades/filters(/branch/:branch_id/group/:group_id/sprint/:sprint_id/lesson/:lesson_id/page/:page_id)' => 'dashboard#grades_filters', as: :dashboard_grades_filters
      match 'dashboard/grades/tech/input(/branch/:branch_id/group/:group_id/sprint/:sprint_id/lesson/:lesson_id)' => "dashboard#grades_input", via: [:get, :post], as: :grades_tech_input
      match 'dashboard/grades/softskill/input(/branch/:branch_id/group/:group_id/sprint/:sprint_id/stype/:stype)' => "dashboard#grades_softskill", via: [:get,:post], as: :grades_softskill_input
      get 'dashboard/grades_filter'
      get 'dashboard/attendance'
      get 'dashboard/student_ranking'
    end

    namespace :admin do
      resources :badges
      resources :soft_skills
      resources :questions
      resources :reviews
      resources :users, except: [:index] do
        get 'group/:group_id' => 'users#group', on: :collection
      end
      resources :sprints do
        get 'group/:group_id' => 'sprints#group_sprints', on: :collection
      end

      resources :tracks do
        resources :courses do
          resources :units do
            resources :lessons do
              resources :pages
            end
          end
        end
      end

      get 'dashboard' => 'dashboard#index', :as => :dashboard
      get 'page_visibility' => 'dashboard#page_visibility', :as => :page_visibility
      post 'save_visibility' => 'dashboard#save_visibility', :as => :save_visibility
      get 'users(/branch/:branch_id)' => 'users#index', :as => :users_index
      post 'change_user_status' => 'users#change_user_status', :as => :change_user_status
    end

    get 'tracks/:id' => 'admin/tracks#show_user_track', :as => :show_track
    get 'tracks/:track_id/courses/:id' => 'admin/courses#show_details', :as => :course_details
    get 'tracks/:track_id/courses/:course_id/units/:unit_id/lessons/:id/' => "admin/lessons#show", :as => :lesson_details
    get 'tracks/:track_id/courses/:course_id/units/:unit_id/lessons/:lesson_id/pages/:id' => "admin/pages#show", :as => :lesson_page_details


    get 'mycourses/:course_id/u/:unit_id/l/:id' => 'admin/lessons#show', :as => :mycourse_unit_lesson
    get 'mycourses/:course_id/u/:unit_id/l/:lesson_id/p/:id' => 'admin/pages#show', :as => :mycourse_unit_lesson_page
    get 'codereview' => 'profile#codereview', :as => :codereview
    get 'myprofile(/:sprint_id)' => 'profile#myprofile', :as => :myprofile
    get 'codereview' => 'profile#codereview', :as => :code_review

    post 'saveAnswer' => 'admin/pages#saveAnswer'
    post 'saveAnswers' => 'admin/pages#saveAnswers'
    post 'saveQuestion' => 'admin/pages#saveQuestion'

    get 'selection' => 'profile#selection', :as => :selection
    get 'selection_success' => 'profile#selection_success', :as => :selection_success

    root :to => 'admin/tracks#show_user_track'
  end

  get 'admission' => 'profile#admission', :as => :admission
  get 'admission_success' => 'profile#admission_success', :as => :admission_success

  devise_for :users,
   path: "",
   path_names: {
    sign_in: "login",
    sign_out: "logout",
    sign_up: "signup"
   },
   controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
end

app/views/admin/pages/_form.html.erb
<% content_for :scripts do %>
  <script>
    $(document).ready(function() {
      CAPITAN.page.form.init();
    });
  </script>
<% end %>

<%= simple_nested_form_for([:admin,@track,@course,@unit,@lesson,@page]) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :sequence %><br/>
    <%= f.input :title %>
    <%= f.input :show_title %><br/>
    <%= f.input :code %><br/>
    <%= f.input :points, label: "Points" %>
    <%= f.input :page_type,
      :collection => [['Material','material'],['Pre-work','prework'],['Quiz','quiz'],
      ['Exercise','exercise'],['Solution','solution'],['Retrospective','retrospective'],
      ['Code Review', 'codereview'], ['Notas', 'score']] %><br>
    <%= render :partial=> 'admin/pages/form/material_fields', :locals => {:f => f} %>
    <%= render :partial=> 'admin/pages/form/quiz_fields', :locals => {:f => f} %>
    <%= render :partial=> 'admin/pages/form/exercise_fields', :locals => {:f => f} %>
    <%= render :partial=> 'admin/pages/form/solution_fields', :locals => {:f => f} %>
    <%= render :partial=> 'admin/pages/form/peerreview_fields', :locals => {:f => f} %>
    <%= render :partial=> 'admin/pages/form/html_fields', :locals => {:f => f} %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-primary page-submit-form" %>
    <%= link_to 'Cancelar', [:admin,@track,@course,@unit,@lesson],:class => "btn btn-danger" %>
  </div>
<% end %>

app/views/admin/pages/edit.html.erb
<div class="container-fluid p-20">
    <div class="page-header">
        <h1>Editar Página</h1>    
    </div>
    <%= render 'form' %>
</div>

app/views/admin/pages/index.html.erb
<div class="container-fluid p-20">
  <div class="page-header clearfix">
    <h1 class="pull-left">Páginas</h1>
    <div class="pull-right">
      <%= link_to 'Crear Nueva Página', new_track_course_unit_lesson_page_path(@track,@course,@lesson,@unit), :class => "btn btn-primary btn-new" %>
    </div>
  </div>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Código</th>
        <th>Título</th>
        <th>Tipo</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @pages.order(:sequence).each do |page| %>
        <tr>
          <td><%= page.sequence %></td>
          <td><%= page.code %></td>
          <td><%= page.title %></td>
          <td><%= page.page_type %></td>
          <td>
            <%= link_to 'Ver página', mycourse_unit_page_path(@course,@unit,page) %>  |
            <%= link_to 'Editar', edit_course_unit_page_path(@course,@unit,page) %>  |
            <%= link_to 'Eliminar', [@track,@course,@unit,page], method: :delete, data: { confirm: '¿Está seguro?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/pages/new.html.erb
<div class="container-fluid p-20">
    <div class="page-header">
        <h1>Nueva Página</h1>
    </div>
    <%= render 'form' %>
</div>

app/views/admin/pages/show.html.erb
<div class="page pb-0">
  <%= render 'admin/pages/show/navigation' %>
  <div class="content">
    <% if @page.show_title %>
      <h3 class="page-title text-center"><%= @page.title %></h3>
      <div class="breakline"></div>
    <% end %>
    <%= render 'admin/pages/show/material' if @page.page_type == 'material' %>
    <%= render 'admin/pages/show/html' if @page.page_type == 'prework' %>
    <%= render 'admin/pages/show/quiz' if ['quiz','retrospective','codereview'].include?(@page.page_type) %>
    <%= render 'admin/pages/show/editor' if @page.page_type == 'editor' %>
    <%= render 'admin/pages/show/questions' if @page.page_type == 'questions' %>
    <%= render 'admin/pages/show/exercise' if @page.page_type == 'exercise' %>
    <%= render 'admin/pages/show/solution' if @page.page_type == 'solution' %>
    <%= render 'admin/pages/show/score' if @page.page_type == 'score' %>
  </div>
</div>