config/routes.rb
Rails.application.routes.draw do

  authenticate :user do

    namespace :employer do
      get 'dashboard/coders'
      get 'dashboard/profile/:user_id' => 'dashboard#profile', as: :student_profile
    end

    namespace :student do
      get 'dashboard/home'
      get 'dashboard/performance'
      get 'dashboard/tracks'
      get 'dashboard/resources'
      get 'tracks/:id' => 'tracks#show', as: :tracks
    end

    namespace :teacher do
      get 'dashboard' => redirect('teacher/dashboard/grades/filters')
      get 'dashboard/grades' => redirect('teacher/dashboard/grades/filters')
      get 'dashboard/class_stats'
      get 'dashboard/student_status'
      get 'dashboard/teacher_stats'
      get 'dashboard/grades/filters(/branch/:branch_id/group/:group_id/sprint/:sprint_id/lesson/:lesson_id/page/:page_id)' => 'dashboard#grades_filters', as: :dashboard_grades_filters
      match 'dashboard/grades/tech/input(/branch/:branch_id/group/:group_id/sprint/:sprint_id/lesson/:lesson_id)' => "dashboard#grades_input", via: [:get, :post], as: :grades_tech_input
      match 'dashboard/grades/softskill/input(/branch/:branch_id/group/:group_id/sprint/:sprint_id/stype/:stype)' => "dashboard#grades_softskill", via: [:get,:post], as: :grades_softskill_input
      get 'dashboard/grades_filter'
      get 'dashboard/attendance'
      get 'dashboard/student_ranking'
    end

    namespace :admin do
      resources :badges
      resources :soft_skills
      resources :questions
      resources :reviews
      resources :users, except: [:index] do
        get 'group/:group_id' => 'users#group', on: :collection
      end
      resources :sprints do
        get 'group/:group_id' => 'sprints#group_sprints', on: :collection
      end

      resources :tracks do
        resources :courses do
          resources :units do
            resources :lessons do
              resources :pages
            end
          end
        end
      end

      get 'dashboard' => 'dashboard#index', :as => :dashboard
      get 'page_visibility' => 'dashboard#page_visibility', :as => :page_visibility
      post 'save_visibility' => 'dashboard#save_visibility', :as => :save_visibility
      get 'users(/branch/:branch_id)' => 'users#index', :as => :users_index
      post 'change_user_status' => 'users#change_user_status', :as => :change_user_status
    end

    get 'tracks/:id' => 'admin/tracks#show_user_track', :as => :show_track
    get 'tracks/:track_id/courses/:id' => 'admin/courses#show_details', :as => :course_details
    get 'tracks/:track_id/courses/:course_id/units/:unit_id/lessons/:id/' => "admin/lessons#show", :as => :lesson_details
    get 'tracks/:track_id/courses/:course_id/units/:unit_id/lessons/:lesson_id/pages/:id' => "admin/pages#show", :as => :lesson_page_details


    get 'mycourses/:course_id/u/:unit_id/l/:id' => 'admin/lessons#show', :as => :mycourse_unit_lesson
    get 'mycourses/:course_id/u/:unit_id/l/:lesson_id/p/:id' => 'admin/pages#show', :as => :mycourse_unit_lesson_page
    get 'codereview' => 'profile#codereview', :as => :codereview
    get 'myprofile(/:sprint_id)' => 'profile#myprofile', :as => :myprofile
    get 'codereview' => 'profile#codereview', :as => :code_review

    post 'saveAnswer' => 'admin/pages#saveAnswer'
    post 'saveAnswers' => 'admin/pages#saveAnswers'
    post 'saveQuestion' => 'admin/pages#saveQuestion'

    get 'selection' => 'profile#selection', :as => :selection
    get 'selection_success' => 'profile#selection_success', :as => :selection_success

    root :to => 'admin/tracks#show_user_track'
  end

  get 'admission' => 'profile#admission', :as => :admission
  get 'admission_success' => 'profile#admission_success', :as => :admission_success

  devise_for :users,
   path: "",
   path_names: {
    sign_in: "login",
    sign_out: "logout",
    sign_up: "signup"
   },
   controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
end

app/views/admin/pages/show/_editor.html.erb
<% content_for :scripts do %>
  <script>
    $(document).ready(function() {
      CAPITAN.page.show.editor.init({
        initial_state: $("#initial_state").text(),
        next_page_url: '<%= mycourse_unit_lesson_page_url(@course,@unit,@next_lesson,@next_page) %>',
        save_answer_title: '<%= @page.success_message.split("|")[0] %>',
        save_answer_text: '<%= @page.success_message.split("|")[1]%>',
        page_id: <%= @page.id %>,
        user_id: <%= current_user.id %>,
        videotip_url: '<%= @page.videotip %>'
      });
      
      $(".start-over").click(function(e) {
        e.preventDefault();
        CAPITAN.page.show.editor.startOver();
      });
      
      $(".save").click(function(e) {
        e.preventDefault();
        CAPITAN.page.show.editor.save(<%= @page.auto_corrector %>);
      });
      
      $(".check-video-again").click(function(e) {
        e.preventDefault();
        CAPITAN.page.show.editor.checkVideoAgain();
      });
    });
  </script>
<% end %>
<div class="container-fluid plr-20x">
    <div class="instructions">
      <%= @page.instructions %>
    </div>
    <div class="editors clearfix">
        <div class="col-sm-6" style="padding-left:0px;padding-right:3px;position:relative;">
          <h3>Editor</h3>
          <textarea id="solution" style="display:none"><%= @page.solution%></textarea>
          <textarea id="initial_state" style="display:none"><%= @page.initial_state %></textarea>
          <textarea id="code" name="code" placeholder="Tu código va aquí..."><%= !@page.answers.where(:user_id => current_user.id).empty? && !@page.answers.where(:user_id => current_user.id).first.result.blank? ? @page.answers.where(:user_id => current_user.id).first.result : @page.initial_state  %></textarea>
        </div>
        <div class="col-sm-6" style="padding-left:3px;padding-right:0px;">
          <h3>Navegador</h3>
          <iframe id="preview" class="preview"></iframe>
        </div>
    </div>
    <span class="editor-notes"><strong class="yellow">Nota:</strong>&nbsp;Presionar <strong>F11</strong> dentro del editor para pantalla completa y <strong>ESC</strong> para regresar al estado normal</span>
    <div class="actions">
      <div class="text-center">
        <% if !@page.videotip.empty? %>
          <a href="#" class="check-video-again btn btn-lg btn-info">Volver al video</a>
        <% end %>
        <a href="#" class="start-over btn btn-lg btn-info">Empezar de nuevo</a>
        <a href="#" class="save btn btn-lg btn-success">Guardar y Continuar</a>
      </div>
    </div>
</div>

app/views/admin/pages/show/_exercise.html.erb
<% content_for :scripts do %>
  <script>
    $(document).ready(function() {
      CAPITAN.page.show.excercise.init($(".exercise_instructions"));
    });
  </script>
<% end %>
<div class="container-fluid plr-20x">
    <div class="exercise_instructions">
      <%= @page.excercise_instructions %>
    </div>
    <% if @page.document.file? %>
      <h2>Materiales</h2>
      Descarga todos los materiales necesario para realizar el ejercicio aqui
      <%= link_to @page.document.url do %>
         <i class="fa fa-file-archive-o"></i>
      <% end %>
    <% end %>
</div>

app/views/admin/pages/show/_html.html.erb
<div class="container-fluid">
    <div class="row">
      <%= raw @page.html %>
    </div>
</div>

app/views/admin/pages/show/_material.html.erb
<div class="outer-container <%="hidden" if @page.page_type != "material" %>">
    <div class="inner-container text-center">
        <div id="slide-container" class="ph-28 <%="hidden" if @page.material_type != "slide" %>">
            <iframe
            src="<%= @page.slide_url %>"
            frameborder="0"
            width="715"
            height="567"
            allowfullscreen="true"
            mozallowfullscreen="true"
            webkitallowfullscreen="true"></iframe>
        </div>
        <div id="video-container" class="<%="hidden" if @page.material_type != "video" %>">
            <div class="video-overlay" style="display: none;">
                <% if @course != nil and @unit != nil and @next_lesson != nil and @next_page != nil %>
                  <%= link_to 'Continuar', lesson_page_details_path(@track,@course,@unit,@next_lesson,@next_page),:class => "btn btn-lg btn-primary" %>
                <% end %>
                <br><br>
                <a href="#" class="rewind-video">
                  <i class="fa fa-undo fa-2x"></i> Ver de nuevo
                </a>
            </div>
            <div id="video-content"></div>
        </div>
        <div id="blog-container" class="<%="hidden" if @page.material_type != "blog" %>">
          <%= raw @page.html %>
        </div>
        <!-- <div class="text-center mt-20">
            <% if @course != nil and @unit != nil and @next_lesson != nil and @next_page != nil %>
                <%= link_to 'Continuar', lesson_page_details_path(@track,@course,@unit,@next_lesson,@next_page),:class => "btn btn-lg btn-warning" %>
            <% end %>
        </div> -->
    </div>
</div>


<% content_for :scripts do %>
  <script>
    $(document).ready(function() {
      CAPITAN.page.show.video.init({
        videoId: "<%= @page.video_url %>"
      });

      $(".rewind-video").click(function(e) {
          e.preventDefault();
          CAPITAN.page.show.video.rewind();
      });

    });

    function onYouTubeIframeAPIReady() {
      CAPITAN.page.show.video.onYouTubePlayerAPIReady();
    }
  </script>
<% end %>

app/views/admin/pages/show/_navigation.html.erb
  <div class="navigation full-height pb-70-xs ph-21-xs">
    <div class="clearfix switch-movil">
      <div class="pull-left">
        <%= link_to image_tag("laboratoria-white.svg",alt: "Laboratoria código que transforma", class: "mt-14", width: "150px"), root_path %>
      </div>
      <div class="pull-right">
        <div class="switch">
          <div class="menu-toggle"></div>
        </div>
      </div>
    </div>
    <div class="breadcrumb mt-21-xs">
      <%= link_to course_details_path(@track,@course) do %>
        <i class="fa fa-arrow-circle-o-left"></i> Volver
      <% end %>
    </div>
    <!--<hr class="nav-divider">-->
    <h2 class="unit-title text-left light" style=""><%= @lesson.title %></h2>
    <% if @lesson.lesson_plan %>
      <a href="<%= @lesson.lesson_plan %>" target="_blank" class="text-white ml-7">
        <i class="fa fa-chevron-right text-primary" aria-hidden="true"></i>
        <span class="thin">Lesson Plan</span>
      </a>
    <% end %>
    <div class="panel-group mb-0" id="accordion" role="tablist" aria-multiselectable="true">
      <div class="panel panel-default border-gray-dark">
        <div class="panel-heading bg-collapse" role="tab" id="headingOne" style="position:relative">
          <h4 class="panel-title  square-pages ml-28 lh-md <%="active" if @page.page_type == "material" %>">
            <a role="button" class="text-uppercase text-white" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="<%= if @page.page_type == "material" then "true" else "false" end %>" aria-controls="collapseOne">
              Material
            </a>
          </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse <%="in" if @page.page_type == "material" %>" role="tabpanel" aria-labelledby="headingOne">
          <div class="panel-body ph-7 pv-0 bg-gray-dark border-gray-dark">
              <ul class="units pl-7">
                <% @lesson.visible_pages_by_type(current_user.branch.id,"material").each do |page| %>
                  <li class="unit-item clearfix <%= page.id == @page.id ? "active": ""%>"
                      title="<%= page.title %>">

                      <%= link_to lesson_page_details_path(@track,@course,@unit,page.lesson,page),
                          :class => "clearfix item" do %>
                        <div class="page-title quote-list pv-7">
                          <%= page.title %>
                        </div>
                      <% end %>
                  </li>
                <% end %>
              </ul>
          </div>
        </div>
      </div>
      <div class="panel-body pv-0">
        <% @lesson.visible_pages_by_type(current_user.branch.id,"prework").each do |page| %>
          <div class="row">
            <div class="col-xs-8">
              <ul class="pl-28 mb-0 bg-gray-dark">
                <li class="square-pages text-uppercase pv-7 <%="active" if @page.page_type == "prework" %>">
                  <%= link_to "Pretrabajo",lesson_page_details_path(@track,@course,@unit,page.lesson,page),class: "text-white" %>
                </li>
              </ul>
            </div>
            <% if page.points != nil and page.points > 0 %>
              <div class="col-xs-4">
                <ul class="bg-gray-dark mb-0">
                  <li class="pv-7">(<%= pluralize page.points, "pt" %>)</li>
                </ul>
              </div>
            <% end %>
          </div>
        <% end %>
        <% @lesson.visible_pages_by_type(current_user.branch.id,"quiz").each do |page| %>
          <div class="row">
            <div class="col-xs-8">
              <ul class="pl-28 mb-0 bg-gray-dark">
                <li class="square-pages text-uppercase pv-7 <%="active" if @page.page_type == "quiz" %>">
                  <%= link_to "quiz",lesson_page_details_path(@track,@course,@unit,page.lesson,page),class: "text-white" %>
                </li>
              </ul>
            </div>
            <div class="col-xs-4">
              <ul class="bg-gray-dark mb-0">
                <li class="pv-7">(<%= pluralize page.points, "pt" %>)</li>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
      <% if @lesson.has_visible_pages_by_type(current_user.branch.id,"exercise") %>
      <div class="panel panel-default border-gray-dark">
        <div class="panel-heading pv-7 bg-collapse" role="tab" id="headingTwo">
          <div class="row">
            <div class="col-xs-8">
              <h4 class="panel-title square-pages ml-28 lh-md <%="active" if @page.page_type == "exercise" %>">
                <a class="collapsed text-uppercase text-white" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="<%= if @page.page_type == "exercise" then "true" else "false" end %>" aria-controls="collapseTwo">
                  EJERCICIOS
                </a>
              </h4>
            </div>
            <div class="col-xs-4">
              <span class="pv-7 text-white">(<%= pluralize @lesson.total_points_by_type("exercise"), "pt" %>)</span>
            </div>
          </div>
        </div>
        <div id="collapseTwo" class="panel-collapse collapse <%="in" if @page.page_type == "exercise" %>" role="tabpanel" aria-labelledby="headingTwo">
          <div class="panel-body ph-7 pv-0 bg-gray-dark border-gray-dark">
            <% @lesson.visible_pages_by_type(current_user.branch.id,"exercise").each do |page| %>
              <div class="row">
                <div class="col-xs-8">
                  <ul class="bg-gray-dark mb-0">
                    <li class="square-pages-list fz-14 ml-42 pv-7 <%="active" if page.id == @page.id %>">
                      <%= link_to page.title,lesson_page_details_path(@track,@course,@unit,page.lesson,page) %>
                    </li>
                  </ul>
                </div>
                <div class="col-xs-4">
                  <ul class="bg-gray-dark">
                    <li class="pv-7 fz-14">(<%= pluralize page.points, "pt" %>)</li>
                  </ul>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
      <% if @lesson.has_visible_pages_by_type(current_user.branch.id,"solution") %>
        <div class="panel panel-default border-gray-dark">
        <div class="panel-heading pv-7 bg-collapse" role="tab" id="headingThree">
          <div class="row">
            <div class="col-xs-8">
              <h4 class="panel-title square-pages ml-28 lh-md <%="active" if @page.page_type == "solution" %>">
                <a class="collapsed text-uppercase text-white" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="<%= if @page.page_type == "solution" then "true" else "false" end %>" aria-controls="collapseThree">
                  SOLUCIONARIO
                </a>
              </h4>
            </div>
            <div class="col-xs-4">
              <span class="pv-7 text-white">(<%= pluralize @lesson.total_points_by_type("solution"), "pt" %>)</span>
            </div>
          </div>

        </div>
        <div id="collapseThree" class="panel-collapse collapse <%="in" if @page.page_type == "solution" %>" role="tabpanel" aria-labelledby="headingThree">
          <div class="panel-body ph-7 pv-0 bg-gray-dark border-gray-dark">
            <% @lesson.visible_pages_by_type(current_user.branch.id,"solution").each do |page| %>
              <div class="row">
                <div class="col-xs-8">
                  <ul class="bg-gray-dark mb-0">
                    <li class="square-pages-list fz-14 ml-42 pv-7 <%="active" if page.id == @page.id %>">
                      <%= link_to page.title,lesson_page_details_path(@track,@course,@unit,page.lesson,page),class: "text-white" %>
                    </li>
                  </ul>
                </div>
                <% if page.points > 0 %>
                  <div class="col-xs-4">
                    <ul class="bg-gray-dark">
                      <li class="pv-7 fz-14">(<%= pluralize page.points, "pt" %>)</li>
                    </ul>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <div class="panel-body pt-0">
      <% if @lesson.has_visible_pages_by_type(current_user.branch.id,"retrospective") %>
        <% @lesson.visible_pages_by_type(current_user.branch.id,"retrospective").each do |page| %>
          <div class="row">
            <div class="col-xs-8">
              <ul class="pl-28 bg-gray-dark mb-0">
                <li class="square-pages text-uppercase pv-7 <%="active" if @page.page_type == "retrospective" %>">
                  <%= link_to "AUTOEVALUACIÓN",lesson_page_details_path(@track,@course,@unit,page.lesson,page),class: "text-white" %>
                </li>
              </ul>
            </div>
            <div class="col-xs-4">
              <ul class="bg-gray-dark mb-0">
                <li class="pv-7">(<%= pluralize page.points, "pt" %>)</li>
              </ul>
            </div>
          </div>
        <% end %>
      <% end %>
      <% if @lesson.has_visible_pages_by_type(current_user.branch.id,"codereview") %>
        <% @lesson.visible_pages_by_type(current_user.branch.id,"codereview").each do |page| %>
          <div class="row">
            <div class="col-xs-8">
              <ul class="pl-28 bg-gray-dark mb-0">
                <li class="square-pages text-uppercase pv-7 <%="active" if @page.page_type == "codereview" %>">
                  <%= link_to "Code Review",lesson_page_details_path(@track,@course,@unit,page.lesson,page),class: "text-white" %>
                </li>
              </ul>
            </div>
            <div class="col-xs-4">
              <ul class="bg-gray-dark mb-0">
                <li class="pv-7">(<%= pluralize page.points, "pt" %>)</li>
              </ul>
            </div>
          </div>
        <% end %>
      <% end %>
      <% if @lesson.has_visible_pages_by_type(current_user.branch.id,"score") %>
        <% @lesson.visible_pages_by_type(current_user.branch.id,"score").each do |page| %>
          <div class="row">
            <div class="col-md-8">
              <ul class="pl-28 bg-gray-dark mb-0">
                <li class="square-pages text-uppercase pv-7 <%="active" if @page.page_type == "score" %>">
                  <%= link_to "Puntos",lesson_page_details_path(@track,@course,@unit,page.lesson,page),class: "text-white" %>
                </li>
              </ul>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/admin/pages/show/_questions.html.erb
<% content_for :scripts do %>
  <script>
    $(document).ready(function() {
        $(".next-step").click(function(e) {
          e.preventDefault();
          CAPITAN.page.show.question.saveQuestion(<%= @page.id %>)
        });
        
        $(".next-step-finished").click(function(e) {
          e.preventDefault();
          window.location = '<%= mycourse_unit_lesson_page_url(@course,@unit,@next_lesson,@next_page) %>';
        }); 
    });
  </script>
<% end %>    
<div class="container-fluid plr-20x">
    <div class="questions-slider">
      <% if @page.getCurrentQuestionGroupId(current_user) != "MAX" %>
      <div class="question-span">
        <h3>Pregunta <span id="sequence"><%= @page.getCurrentSequence(current_user) %></span> de <%= @page.question_groups.size %></h3>
        <% @page.question_groups.order(:sequence).each do |question_group| %>
          <div class="question" 
               style="<%= @page.getCurrentQuestionGroupId(current_user).to_i == question_group.id ? "" : "display:none;" %>"
               data-question-id="<%= question_group.id %>">
            <h3><%= question_group.question.description %></h3>
            <ul style="margin-bottom: 30px;">
              <% question_group.question.options.each do |option| %>
                <li>
                  <table>
                    <tr>
                      <td style="width:2%;padding-right:10px;">
                        <input type="radio" 
                               id="q-<%=option.id %>" 
                               name="question-option" 
                               value="<%= option.id %>" 
                               data-question-id="<%= question_group.id %>">
                      </td>
                      <td><label for="q-<%=option.id %>" style="cursor:pointer;font-weight:300;"><%= option.description %></label></td>
                    </tr>
                  </table>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>  
        <a href="#" class="btn btn-primary next-step">Guardar y Continuar</a>
      </div>
      <% end %>
      <div class="question-finished" style="<%= @page.getCurrentQuestionGroupId(current_user) != "MAX" ? "display:none;" : "" %>">
        <h4>Gracias por responder todas las preguntas pero los cuestionarios sólo se pueden responder una vez.</h4>
        <a href="#" class="btn btn-primary next-step-finished">Continuar</a>
      </div>
    </div>
</div>

app/views/admin/pages/show/_score.html.erb
<div class="outer-container score-pages">
    <div class="inner-container text-center">
      <div class="text-center mt-20">
        <% if Submission.where(user_id: current_user.id).count > 0 %>
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th></th>
                  <th style="text-align:center;">Puntos Alcanzados</th>
                  <th style="text-align:center;">% del Total de Puntos Disponibles</th>
                  <th style="text-align:center;">Promedio Salón</th>
                </tr>
              </thead>
              <tbody>
                <% @pages_points.each do |page| %>
                  <tr>
                    <td style="text-align:left;font-weight:bold;"><%= page[:page_title] %></td>
                    <td><%= "#{page[:student_points].round(2)} / #{page[:page_points].round(2)}" %></td>
                    <td><%= (page[:student_points] / page[:page_points]*100).round(2) %> %</td>
                    <td><%= page[:average_points].round(2) %></td>
                  </tr>
                <% end %>
              </tbody>
              <tfooter>
                <tr>
                  <th style="text-align:left;font-weight:bold;">Total</th>
                  <td><%= "#{@total_student_points.round(2)} / #{@total_page_points.round(2)}" %></td>
                  <td><%= (@total_student_points / @total_page_points * 100).round(2) %> %</td>
                  <td><%= @total_average_points.round(2) %></td>
                </tr>
              </tfooter>
            </table>
          </div>
        <% else %>
          <p>Aun no se pueden visualizar tus puntos.</p>
        <% end %>
      </div>
    </div>
</div>

app/views/admin/pages/show/_slides.html.erb
<div class="outer-container">
    <div class="inner-container text-center">
      <div id="video-content">
        <iframe 
        src="<%= @page.slide_url %>" 
        frameborder="0" 
        width="715" 
        height="567" 
        allowfullscreen="true" 
        mozallowfullscreen="true" 
        webkitallowfullscreen="true"></iframe>
      </div>
      <div class="text-center mt-20">
        <% if @course != nil and @unit != nil and @next_lesson != nil and @next_page != nil %>
          <%= link_to 'Saltar Slide', mycourse_unit_lesson_page_path(@course,@unit,@next_lesson,@next_page),:class => "btn btn-lg btn-warning" %>
        <% end %>
      </div>
    </div>
</div> 

app/views/admin/pages/show/_solution.html.erb
<div class="outer-container <%="hidden" if @page.page_type != "solution" %>">
  <div class="inner-container text-center">
    <h2>Solucionario</h2>
    Descarga el solucionario del ejercicio aqui 
    <%= link_to @page.solution_file.url do %>
      <i class="fa fa-file-archive-o"></i>
    <% end %><br><br>
    <div class="clearfix">
      <% @page.video_solution.split(',').each do |solution| %>
        <div>
          <iframe width="560" height="315" src="<%= solution %>" frameborder="0" allowfullscreen></iframe>
        </div>        
      <% end %>
    </div> 
  </div>
</div>

app/views/admin/pages/show/_video.html.erb
<% content_for :scripts do %>
  <script>
    $(document).ready(function() {
      CAPITAN.page.show.video.init({
        videoId: "<%#= @page.video_url unless @page.video_url %>"
      });

      $(".rewind-video").click(function(e) {
          e.preventDefault();
          CAPITAN.page.show.video.rewind();
      });

    });

    function onYouTubeIframeAPIReady() {
      CAPITAN.page.show.video.onYouTubePlayerAPIReady();
    }
  </script>
<% end %>
<div class="outer-container">
    <div class="inner-container text-center">
      <div class="video-overlay" style="display: none;">
        <%#= link_to 'Continuar', mycourse_unit_lesson_page_path(@course,@unit,@next_lesson,@next_page),:class => "btn btn-lg btn-primary" %>
        <br><br>
        <a href="#" class="rewind-video">
          <i class="fa fa-undo fa-2x"></i> Ver de nuevo
        </a>
      </div>
      <div id="video-content"></div>
      <div class="text-center mt-20">
        <% if @course != nil and @unit != nil and @next_lesson != nil and @next_page != nil %>
          <%#= link_to 'Saltar video', mycourse_unit_lesson_page_path(@course,@unit,@next_lesson,@next_page),:class => "btn btn-lg btn-warning" %>
        <% end %>
      </div>
    </div>
</div>