config/routes.rb
Rails.application.routes.draw do

  authenticate :user do

    namespace :employer do
      get 'dashboard/coders'
      get 'dashboard/profile/:user_id' => 'dashboard#profile', as: :student_profile
    end

    namespace :student do
      get 'dashboard/home'
      get 'dashboard/performance'
      get 'dashboard/tracks'
      get 'dashboard/resources'
      get 'tracks/:id' => 'tracks#show', as: :tracks
    end

    namespace :teacher do
      get 'dashboard' => redirect('teacher/dashboard/grades/filters')
      get 'dashboard/grades' => redirect('teacher/dashboard/grades/filters')
      get 'dashboard/class_stats'
      get 'dashboard/student_status'
      get 'dashboard/teacher_stats'
      get 'dashboard/grades/filters(/branch/:branch_id/group/:group_id/sprint/:sprint_id/lesson/:lesson_id/page/:page_id)' => 'dashboard#grades_filters', as: :dashboard_grades_filters
      match 'dashboard/grades/tech/input(/branch/:branch_id/group/:group_id/sprint/:sprint_id/lesson/:lesson_id)' => "dashboard#grades_input", via: [:get, :post], as: :grades_tech_input
      match 'dashboard/grades/softskill/input(/branch/:branch_id/group/:group_id/sprint/:sprint_id/stype/:stype)' => "dashboard#grades_softskill", via: [:get,:post], as: :grades_softskill_input
      get 'dashboard/grades_filter'
      get 'dashboard/attendance'
      get 'dashboard/student_ranking'
    end

    namespace :admin do
      resources :badges
      resources :soft_skills
      resources :questions
      resources :reviews
      resources :users, except: [:index] do
        get 'group/:group_id' => 'users#group', on: :collection
      end
      resources :sprints do
        get 'group/:group_id' => 'sprints#group_sprints', on: :collection
      end

      resources :tracks do
        resources :courses do
          resources :units do
            resources :lessons do
              resources :pages
            end
          end
        end
      end

      get 'dashboard' => 'dashboard#index', :as => :dashboard
      get 'page_visibility' => 'dashboard#page_visibility', :as => :page_visibility
      post 'save_visibility' => 'dashboard#save_visibility', :as => :save_visibility
      get 'users(/branch/:branch_id)' => 'users#index', :as => :users_index
      post 'change_user_status' => 'users#change_user_status', :as => :change_user_status
    end

    get 'tracks/:id' => 'admin/tracks#show_user_track', :as => :show_track
    get 'tracks/:track_id/courses/:id' => 'admin/courses#show_details', :as => :course_details
    get 'tracks/:track_id/courses/:course_id/units/:unit_id/lessons/:id/' => "admin/lessons#show", :as => :lesson_details
    get 'tracks/:track_id/courses/:course_id/units/:unit_id/lessons/:lesson_id/pages/:id' => "admin/pages#show", :as => :lesson_page_details


    get 'mycourses/:course_id/u/:unit_id/l/:id' => 'admin/lessons#show', :as => :mycourse_unit_lesson
    get 'mycourses/:course_id/u/:unit_id/l/:lesson_id/p/:id' => 'admin/pages#show', :as => :mycourse_unit_lesson_page
    get 'codereview' => 'profile#codereview', :as => :codereview
    get 'myprofile(/:sprint_id)' => 'profile#myprofile', :as => :myprofile
    get 'codereview' => 'profile#codereview', :as => :code_review

    post 'saveAnswer' => 'admin/pages#saveAnswer'
    post 'saveAnswers' => 'admin/pages#saveAnswers'
    post 'saveQuestion' => 'admin/pages#saveQuestion'

    get 'selection' => 'profile#selection', :as => :selection
    get 'selection_success' => 'profile#selection_success', :as => :selection_success

    root :to => 'admin/tracks#show_user_track'
  end

  get 'admission' => 'profile#admission', :as => :admission
  get 'admission_success' => 'profile#admission_success', :as => :admission_success

  devise_for :users,
   path: "",
   path_names: {
    sign_in: "login",
    sign_out: "logout",
    sign_up: "signup"
   },
   controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action do
    check_allowed_roles(current_user, ["assistant","teacher","admin"])
  end

  layout "admin"

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to [:admin,@review], notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to [:admin,@review], notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to admin_reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:answer, :page_id, :question_id, :user_id, :reviewer_id)
    end
end

app/views/admin/reviews/_form.html.erb
<%= simple_form_for @review do |f| %>
  <div class="form-inputs">
    <%= f.association :page %><br>
    <%= f.association :question %><br>
    <%= f.association :user %><br>
    <%= f.association :reviewer %><br>
    <%= f.input :answer %><br>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
    <%= link_to 'Cancelar', admin_reviews_path, :class => 'btn btn-danger' %>    
  </div>
<% end %>

app/views/admin/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', admin_reviews_path %>

app/views/admin/reviews/index.html.erb
<div class="container-fluid p-20">
  <div class="page-header clearfix">
      <h1 class="pull-left">Reviews</h1>
      <div class="pull-right">
        <%= link_to 'Crear un nuevo review', new_admin_review_path, :class => "btn btn-primary btn-new" %>
      </div>
  </div>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Coder</th>
        <th>Reviewer</th>
        <th>Question</th>
        <th>Answer</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @reviews.each do |review| %>
        <tr>
          <td><%= review.user.profile.name %></td>
          <td><%= review.reviewer.profile.name %></td>
          <td><%= review.question.description %></td>
          <td><%= review.answer %></td>
          <td>
            <%= link_to 'Editar', edit_admin_review_path(review) %>
            <%= link_to 'Eliminar', [:admin,review], method: :delete, data: { confirm: '¿Estás seguro?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/reviews/new.html.erb
<div class="container">
    <div class="p-20">
        <div class="page-header clearfix">
            <h1 class="pull-left">Nuevo Review</h1>
            <div class="pull-right">
                <%= link_to 'Nueva Pregunta', new_admin_question_path, :class => "btn btn-primary btn-new" %>
            </div>
        </div>
        <%= render :partial => 'form' %>
    </div>
</div>

app/views/admin/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_review_path(@review) %> |
<%= link_to 'Back', admin_reviews_path %>