config/routes.rb
Rails.application.routes.draw do

  authenticate :user do

    namespace :employer do
      get 'dashboard/coders'
      get 'dashboard/profile/:user_id' => 'dashboard#profile', as: :student_profile
    end

    namespace :student do
      get 'dashboard/home'
      get 'dashboard/performance'
      get 'dashboard/tracks'
      get 'dashboard/resources'
      get 'tracks/:id' => 'tracks#show', as: :tracks
    end

    namespace :teacher do
      get 'dashboard' => redirect('teacher/dashboard/grades/filters')
      get 'dashboard/grades' => redirect('teacher/dashboard/grades/filters')
      get 'dashboard/class_stats'
      get 'dashboard/student_status'
      get 'dashboard/teacher_stats'
      get 'dashboard/grades/filters(/branch/:branch_id/group/:group_id/sprint/:sprint_id/lesson/:lesson_id/page/:page_id)' => 'dashboard#grades_filters', as: :dashboard_grades_filters
      match 'dashboard/grades/tech/input(/branch/:branch_id/group/:group_id/sprint/:sprint_id/lesson/:lesson_id)' => "dashboard#grades_input", via: [:get, :post], as: :grades_tech_input
      match 'dashboard/grades/softskill/input(/branch/:branch_id/group/:group_id/sprint/:sprint_id/stype/:stype)' => "dashboard#grades_softskill", via: [:get,:post], as: :grades_softskill_input
      get 'dashboard/grades_filter'
      get 'dashboard/attendance'
      get 'dashboard/student_ranking'
    end

    namespace :admin do
      resources :badges
      resources :soft_skills
      resources :questions
      resources :reviews
      resources :users, except: [:index] do
        get 'group/:group_id' => 'users#group', on: :collection
      end
      resources :sprints do
        get 'group/:group_id' => 'sprints#group_sprints', on: :collection
      end

      resources :tracks do
        resources :courses do
          resources :units do
            resources :lessons do
              resources :pages
            end
          end
        end
      end

      get 'dashboard' => 'dashboard#index', :as => :dashboard
      get 'page_visibility' => 'dashboard#page_visibility', :as => :page_visibility
      post 'save_visibility' => 'dashboard#save_visibility', :as => :save_visibility
      get 'users(/branch/:branch_id)' => 'users#index', :as => :users_index
      post 'change_user_status' => 'users#change_user_status', :as => :change_user_status
    end

    get 'tracks/:id' => 'admin/tracks#show_user_track', :as => :show_track
    get 'tracks/:track_id/courses/:id' => 'admin/courses#show_details', :as => :course_details
    get 'tracks/:track_id/courses/:course_id/units/:unit_id/lessons/:id/' => "admin/lessons#show", :as => :lesson_details
    get 'tracks/:track_id/courses/:course_id/units/:unit_id/lessons/:lesson_id/pages/:id' => "admin/pages#show", :as => :lesson_page_details


    get 'mycourses/:course_id/u/:unit_id/l/:id' => 'admin/lessons#show', :as => :mycourse_unit_lesson
    get 'mycourses/:course_id/u/:unit_id/l/:lesson_id/p/:id' => 'admin/pages#show', :as => :mycourse_unit_lesson_page
    get 'codereview' => 'profile#codereview', :as => :codereview
    get 'myprofile(/:sprint_id)' => 'profile#myprofile', :as => :myprofile
    get 'codereview' => 'profile#codereview', :as => :code_review

    post 'saveAnswer' => 'admin/pages#saveAnswer'
    post 'saveAnswers' => 'admin/pages#saveAnswers'
    post 'saveQuestion' => 'admin/pages#saveQuestion'

    get 'selection' => 'profile#selection', :as => :selection
    get 'selection_success' => 'profile#selection_success', :as => :selection_success

    root :to => 'admin/tracks#show_user_track'
  end

  get 'admission' => 'profile#admission', :as => :admission
  get 'admission_success' => 'profile#admission_success', :as => :admission_success

  devise_for :users,
   path: "",
   path_names: {
    sign_in: "login",
    sign_out: "logout",
    sign_up: "signup"
   },
   controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController

  before_action do
    check_allowed_roles(current_user, ["assistant","teacher","admin"])
  end

  layout "admin"

  def index
  end

  def page_visibility
    @branches = Branch.all
    @courses = Course.all
  end

  def save_visibility
    status = "ok"
    message = "success"

    begin
      page_visibility = JSON.parse(params[:page_visibility])
      page_visibility.each do |page_visible|
        pv = PageVisibility.find_or_create_by(page_id: page_visible["page_id"],branch_id: page_visible["branch_id"])
        pv.status = page_visible["status"]
        pv.save
      end
    rescue => exception
      puts exception
      status = "fail"
      message = "We could not save the page visibility"
    end

    render :json => { :status => status, :message => message }
  end
end

app/controllers/employer/dashboard_controller.rb
class Employer::DashboardController < ApplicationController

  before_action do
    check_allowed_roles(current_user, ["employer","admin"])
  end

  layout 'employer'

  def coders
    if current_user.branch.id == 1
      @students = User.includes(:profile).where(role: 1, disable: 0, group_id: [5,21])
      @student_technical_points = Submission.students_technical_points(5) +
                                  Submission.students_technical_points(21)
      @student_hse_points = SoftSkillSubmission.students_technical_points(5) +
                            SoftSkillSubmission.students_technical_points(21)

      @badges_points = User.where(group_id:5).joins(:sprint_badges => :badge).group(:id).pluck(:id,"sum(points)") +
                       User.where(group_id:21).joins(:sprint_badges => :badge).group(:id).pluck(:id,"sum(points)")
    elsif current_user.branch.id == 3
      @students = User.includes(:profile).where(role: 1, disable: 0, group_id: [8,22])
      @student_technical_points = Submission.students_technical_points(8) +
                                  Submission.students_technical_points(22)
      @student_hse_points = SoftSkillSubmission.students_technical_points(8) +
                            SoftSkillSubmission.students_technical_points(22)

      @badges_points = User.where(group_id:8).joins(:sprint_badges => :badge).group(:id).pluck(:id,"sum(points)") +
                       User.where(group_id:22).joins(:sprint_badges => :badge).group(:id).pluck(:id,"sum(points)")
    end

    @students_ordered = @students.map { |e| [e,(@student_technical_points.select { |s| s[0] == e.id }.first != nil ? (@student_technical_points.select { |s| s[0] == e.id }.first)[3] : 0) +
                                               (@student_hse_points.select { |s| s[0] == e.id}.first != nil ? (@student_hse_points.select { |s| s[0] == e.id}.first)[3] : 0) +
                                               (@badges_points.select{ |s| s[0] == e.id}.first != nil ? (@badges_points.select{ |s| s[0] == e.id}.first)[1] : 0) ]}.sort_by  { |k| k[1]*-1 }
  end

  def profile
    @user = User.find(params[:user_id])
    @sprint_badges = @user.sprint_badges.group_by(&:badge).map { |key,value| [key,value.size] }

    @maximum_points = SprintPage.total_points(@user.group_id).map { |e| e[1] }.reduce(&:+)
    @student_points = SprintPage.student_points(@user).map { |e| e[1] }.reduce(&:+)
    @badge_points = @user.sprint_badges.joins(:badge).pluck('badges.points').reduce(&:+)
    @soft_skills_points = SoftSkillSubmission.for_user(@user)
    @avg_soft_skills_points = SoftSkillSubmission.avg_classroom_points(@user)
    @avg_students_points = Submission.avg_all_classroom_points(@user.group_id)

    @student_technical_points = { points: @student_points + (@badge_points != nil ? @badge_points : 0),
                                  max: @maximum_points }
    @student_hse_points = { points: @soft_skills_points.map { |e| e["points"]}.reduce(&:+),
                            max: @soft_skills_points.map { |e| e["max_points"]}.reduce(&:+) }

    @sprints = @user.group.sprints.joins(:pages).where("pages.points > 0 or sprint_pages.points > 0").order(:sequence).distinct
    @sprint_points = Array.new
    @sprints.each do |sprint|
      @sprint_points << {
        name: sprint.name,
        description: sprint.description,
        max: sprint.total_points.map { |e| e[1] }.reduce(&:+),
        points: sprint.student_points(@user).map { |e| e[1] }.reduce(&:+),
        average: Submission.avg_classroom_points(@user.group_id,sprint.id)
      }
    end
  end

  private

  def sum_points data_arr, page_type
    data_arr.map {|e| e[page_type]}.reduce(&:+)
  end

end

app/controllers/student/dashboard_controller.rb
class Student::DashboardController < ApplicationController

  before_action do
    check_allowed_roles(current_user, ["student","assistant","teacher","admin"])
  end

  def home
  end

  def performance
  end

  def tracks
    @user = current_user
    @sprint_badges = @user.sprint_badges.group_by(&:badge).map { |key,value| [key,value.size] }

    @maximum_points = SprintPage.total_points(@user.group_id).map { |e| e[1] }.reduce(&:+)
    @student_points = SprintPage.student_points(@user).map { |e| e[1] }.reduce(&:+)
    @badge_points = @user.sprint_badges.joins(:badge).pluck('badges.points').reduce(&:+)
    @soft_skills_points = SoftSkillSubmission.for_user(@user)

    @student_technical_points = { points: (@student_points != nil ? @student_points : 0) + (@badge_points != nil ? @badge_points : 0),
                                  max: @maximum_points }
    @student_hse_points = { points: @soft_skills_points.map { |e| e["points"]}.reduce(&:+),
                            max: @soft_skills_points.map { |e| e["max_points"]}.reduce(&:+) }

    @tracks = Track.all.order(:sequence)
  end

  def resources
  end

  def surveys
    @tracks = Track.all.order(:sequence)
    @branchs = Branch.all
    @groups = Group.all
    @teachers = ["Lead Teacher","Lead Teacher","Teacher Assistant 1","Teacher Assistant 2", "Teacher Assistant 3"]
    @jedis = ["Ale", "Andrea Lamas","Arabela","Elizabeth","Lalo","Mafe","Malu","Meche","Michelle","Papu"]
    @temas = ['Introducción al desarrollo web', 'HTML/ HTML5 y JavaScript en el navegador','Manejo de comandos básicos de git en la terminal','Pruebas unitarias','Git/ Resolución de conflictos/ Branching model','DOM 101']
  end

end

app/controllers/teacher/dashboard_controller.rb
class Teacher::DashboardController < ApplicationController

  before_action do
    check_allowed_roles(current_user, ["assistant","teacher","admin"])
  end

  layout "teacher"

  def class_stats
  end

  def students
  end

  def teacher_stats
  end

  def grades_filters
      @branches = Branch.all
      @soft_skills = SoftSkill.stypes
      render 'grades_filter'
  end

  def grades_input
    if request.post?
      params[:input][:grades].each { |user_id,grades|
      grades.each { |page_id,grade|
          submission = Submission.find_or_initialize_by(user_id: user_id,page_id:page_id)
          submission.points = grade.first
          submission.save
        }
      }

      params[:page_id] = params[:input][:page_id]
      params[:sprint_id] = params[:input][:sprint_id]
      params[:lesson_id] = params[:input][:lesson_id]
      params[:group_id] = params[:input][:group_id]

      flash[:success] = "Notas grabadas exitosamente"
    end

    @sprint = Sprint.find(params[:sprint_id])
    @group  = Group.find(params[:group_id])
    @lesson = SprintPage.
               joins(:page => :lesson).
               where("sprint_id = ? and coalesce(sprint_pages.points,pages.points) > 0 and lessons.id = ?",params[:sprint_id],params[:lesson_id]).
               pluck("pages.id","coalesce(sprint_pages.points,pages.points) as points","pages.title","lessons.title","pages.page_type").
               group_by { |e| e[3] }.first

    @users  = User.includes(:profile).where(group_id: params[:group_id], role: 1, disable:false)
    @submissions = Submission.where(user_id: @users.map { |u| u.id }).map { |s| [s.page_id,s.user_id,s.points]}
  end

  def grades_softskill
    if request.post?
      for i in 0..params[:input][:users].size
        params[:input][:grades].each { |k,v|
          submission = SoftSkillSubmission.find_or_initialize_by(user_id: params[:input][:users][i],soft_skill_id:k)
          submission.points = v[i]
          submission.save
        }
      end
      params[:sprint_id] = params[:input][:sprint_id]
      params[:group_id] = params[:input][:group_id]
      params[:stype] = params[:input][:stype]
    end

    @sprint = Sprint.find(params[:sprint_id])
    @group  = Group.find(params[:group_id])
    @softskill = SoftSkill.stypes.keys[0].capitalize
    @soft_skills = SprintSoftSkill.where(sprint_id:params[:sprint_id]).joins(:soft_skill).
                   where("soft_skills.stype":params[:stype]).
                   pluck_to_hash("soft_skills.id as id","soft_skills.name as name","coalesce(sprint_soft_skills.points,soft_skills.max_points) as points")
    @users  = User.includes(:profile).where(group_id: params[:group_id], role: 1, disable:false)
    @submissions = SoftSkillSubmission.where(sprint_id:params[:sprint_id],user_id: @users.map { |u| u.id }).map { |s| [s.user_id,s.soft_skill_id,s.points]}

  end

  def grades_filter
    status, message = "ok", "success"
    begin
      case params[:filter]
      when "group"
        result = Group.where(branch_id: params[:options][:branch_id]).pluck(:id, :name)
      when "sprint"
        result = Sprint.where(group_id: params[:options][:group_id]).pluck(:id,:name)
      when "lesson"
        lesson_points = SprintPage.joins(:page => :lesson).
                                   joins(:sprint).
                                   where("sprints.id = ?",params[:options][:sprint_id]).
                                   group("lessons.id, lessons.title").
                                   pluck("lessons.id","lessons.title","coalesce(sum(coalesce(sprint_pages.points,pages.points)),0)")

        result = lesson_points.select { |l| l[2] > 0 }
      end
    rescue => error
      p error
      status = "fail"
      message = "No pudimos obtener el filtro solicitado"
    end
    render :json => { status: status, message: message, data: result }
  end

  def assistance
  end

  def sprints
  end

  def recomendations
  end
end

app/helpers/students/dashboard_helper.rb
module Students::DashboardHelper
  def age birthdate
    now = Time.now.utc.to_date
    now.year - birthdate.year - (birthdate.to_date.change(:year => now.year) > now ? 1 : 0)
  end

  def percentage grades
    points = grades[:points] != nil ? grades[:points] : 0
    return grades[:max] != nil ? round(points * 100.0 / grades[:max]) : 0
  end

  def round num
    i, f = num.to_i, num.to_f
    i == f ? i : f.round(1)
  end
end

app/helpers/teacher/dashboard_helper.rb
module Teacher::DashboardHelper

  def select_points(sprint_page,page)
    return sprint_page.points.nil? ? page.points : sprint_page.points
  end

  def find_submission_points(page_id,user_id,submissions)
    s = submissions.select { |s| s[0] == page_id and s[1] == user_id }
    return !s.empty? ? submissions.select { |s| s[0] == page_id and s[1]== user_id }.first[2] : nil
  end

  def find_soft_skills_submissions_points(user_id,soft_skill_id,submissions)
    s = submissions.select { |s| s[0] == user_id and s[1] == soft_skill_id }
    return s != nil && !s.empty? ? s.first[2] : nil
  end

end

app/views/teacher/dashboard/assistance.html.erb
<h1>Teacher::Dashboard#assistance</h1>
<p>Find me in app/views/teacher/dashboard/assistance.html.erb</p>

app/views/teacher/dashboard/class_stats.html.erb
<h1>Teacher::Dashboard#class_stats</h1>
<p>Find me in app/views/teacher/dashboard/class_stats.html.erb</p>

app/views/teacher/dashboard/grades_filter.html.erb
<% content_for :scripts do %>
<script type="text/javascript">

    var branch_id = "";
    var group_id = "";
    var sprint_id = "";
    var lesson_id = "";
    var area_id = "";

    $(document).ready(function () {

        initFilters();

        $("#filter_branch_id").change(function() {
            branch_id = $(this).val();
            clearFilters([{ filter: "#filter_group_id", blank: "Seleccione una promoción"},
                          { filter: "#filter_sprint_id",blank: "Seleccione un sprint"},
                          { filter: "#filter_area_id",  blank: "Seleccione un área", options: [[1,"Técnico"],[2,"HSE"]] },
                          { filter: "#filter_lesson_id",blank: "Seleccione una lección"}]);
            changeFilter({ filter: "group", options: { branch_id: branch_id } },"#filter_group_id");
        });
        $("#filter_group_id").change(function() {
            group_id = $(this).val();
            clearFilters([{ filter: "#filter_sprint_id",blank: "Seleccione un sprint"},
                          { filter: "#filter_area_id",  blank: "Seleccione un área", options: [[1,"Técnico"],[2,"HSE"]]},
                          { filter: "#filter_lesson_id",blank: "Seleccione una lección"}]);
            changeFilter({ filter: "sprint", options: { group_id: group_id } },"#filter_sprint_id");
        });
        $("#filter_sprint_id").change(function() {
            sprint_id = $(this).val();
            clearFilters([{ filter: "#filter_area_id",  blank: "Seleccione un área", options: [[1,"Técnico"],[2,"HSE"]]},
                          { filter: "#filter_lesson_id",blank: "Seleccione una lección"}]);
            changeFilter({ filter: "lesson", options: { sprint_id: sprint_id } },"#filter_lesson_id");
            $("#filter_soft_skill_id").hide();
            $("#filter_lesson_id").hide();
        });
        $("#filter_lesson_id").change(function() {
            lesson_id = $(this).val();
        });

        $("#filter_area_id").change(function() {
            area_id = parseInt($(this).val());
            switch (area_id) {
              case 1:
                $("#filter_soft_skill_id").hide();
                $("#filter_lesson_id").show();
                break;
              case 2:
                $("#filter_soft_skill_id").show();
                $("#filter_lesson_id").hide();
                break;
            }
        });

        $("form input[type='submit']").click(function(e) {
            e.preventDefault();
            var proceed = true;
            var soft_skill_id = $("#filter_soft_skill_id").val();

            if (branch_id == "" || group_id == "" || sprint_id == "" || area_id == "") {
                alert("Seleccione una sede, grupo, sprint o área de trabajo");
                proceed = false;
            }
            if (area_id == 1 && lesson_id == "") {
                alert("Seleccione una lección");
                proceed = false;
            } else if (area_id == 2 && soft_skill_id == "") {
                alert("Seleccione un soft skill");
                proceed = false;
            }

            if (proceed && area_id == 1) {
                document.location = "<%= teacher_grades_tech_input_path %>/branch/[branch_id]/group/[group_id]/sprint/[sprint_id]/lesson/[lesson_id]"
                .replace("[branch_id]",branch_id)
                .replace("[group_id]",group_id)
                .replace("[sprint_id]",sprint_id)
                .replace("[lesson_id]",lesson_id);
            } else if (proceed &&  area_id == 2) {
                document.location = "<%= teacher_grades_softskill_input_path %>/branch/[branch_id]/group/[group_id]/sprint/[sprint_id]/stype/[stype]"
                .replace("[branch_id]",branch_id)
                .replace("[group_id]",group_id)
                .replace("[sprint_id]",sprint_id)
                .replace("[stype]",soft_skill_id);
            }
        });
    });

    function initFilters() {

    }

    function changeFilter(send_data,filter_to_update) {
        $.get("<%= teacher_dashboard_grades_filter_path %>",send_data,function(result) {
            result.status == "ok" ? addRemoteOptions(filter_to_update,result.data) : alert(result.message);
        });
    }

    function clearFilters(elements) {
        elements.forEach(function (element) {
            clearFilter(element.filter,element.blank, element.options);
        });
    }

    function clearFilter(element, blank, options) {
        var select = $(element);
        select.empty();
        select.append('<option value="">'+blank+'</option>');
        if (options != null) {
          options.forEach(function(option) {
              select.append('<option value="'+option[0]+'">'+option[1]+'</option>');
          });
        }
    }

    function addRemoteOptions(element, options) {
        var select = $(element);
        if (options != null) {
            options.forEach(function(option) {
                select.append('<option value="'+option[0]+'">'+option[1]+'</option>');
            });
        }
    }

</script>
<% end %>
<div class="p-42" id="grade">
    <div class="page-header clearfix flex-title-start">
      <%= image_tag 'grades.png', width: "16", class: "mr-14" %>
      <span class="title-grade">Grades</span>
    </div>
    <div class="row">
      <div class="col-sm-8">
        <%= simple_form_for :filter, url: teacher_grades_tech_input_path do |f| %>
          <%= f.input :branch_id, collection: @branches, label:false, include_blank: "Seleccione una sede",selected: params[:branch_id] %>
          <%= f.input :group_id, collection: [], label: false, include_blank: "Seleccione una promoción" %>
          <%= f.input :sprint_id, collection: [], label: false, include_blank: "Seleccione un sprint" %>
          <%= f.input :area_id, collection: [["Técnico",1],["HSE",2]], label: false, include_blank: "Seleccione un área" %>
          <%= f.input :lesson_id, collection: [], label: false, include_blank: "Seleccione una lección", input_html: {style: "display:none;"} %>
          <%= f.input :soft_skill_id, collection: @soft_skills, label: false, include_blank: "Seleccione un softskill", input_html: {style: "display:none;"} %>
          <%= f.submit "Buscar", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
</div>

app/views/teacher/dashboard/grades_input.html.erb
<div class="container-fluid p-20">
    <ol class="breadcrumb">
      <li><%= link_to "Regresar",teacher_dashboard_grades_filters_path(params[:branch_id],params[:group_id],params[:sprint_id],params[:lesson_id],params[:page_id]), :class => "active" %></li>
    </ol>
    <section class="grades-input">
      <div class="header">
        <h3><%= @lesson[0] %></h3>
        <h4><%= @sprint.name %></h4>
        <h4><%= @group.name %></h4>
      </div>
      <%= simple_form_for :input, url: teacher_grades_tech_input_path do |f| %>
        <%= f.input :sprint_id,as: :hidden, :input_html => {:value => params[:sprint_id]} %>
        <%= f.input :lesson_id,as: :hidden, :input_html => {:value => params[:lesson_id]} %>
        <%= f.input :group_id,as: :hidden, :input_html => {:value => params[:group_id]} %>
        <table class="table table-bordered table-condensed">
            <thead>
                <tr>
                    <th rowspan="2">Estudiante</th>
                    <th colspan="<%= @lesson[1].size %>"><%= @lesson[0] %></th>
                </tr>
                <tr>
                    <% @lesson[1].each do |page| %>
                        <th><%= page[2] %><br />Nota máxima: <%= page[1] %> puntos</th>
                    <% end %>
                </tr>
            </thead>
        <% @users.each do |user| %>
          <tr>
            <td>
              <%= image_tag user.avatar(:student_dashboard), :class => "user-image" if user.avatar.exists? %>
              <h4 class="mt-0"><%= user.profile.name %></h4>
              <p><%= user.code %></p>
            </td>
            <% @lesson[1].each do |page| %>
                <td style="vertical-align:middle;">
                    <% user_points = find_submission_points(page[0],user.id,@submissions) %>
                    <%= f.input :grades, label:false,
                        :input_html => {:type => "number",
                                        :name => "input[grades][#{user.id}][#{page[0]}][]",
                                        :step => "0.1",
                                        :value => (!user_points.nil? ? user_points.round(2) : nil)} %>
                </td>
            <% end %>
          </tr>
        <% end %>
        <tr>
          <td></td>
          <td colspan="<%= @lesson[1].size %>" style="text-align:right">
            <%= f.submit "Guardar Cambios", class: "btn btn-primary" %>
          </td>
        </tr>
        </table>
      <% end %>
    </section>
</div>

app/views/teacher/dashboard/grades_softskill.html.erb
<div class="container-fluid p-20">
    <ol class="breadcrumb">
      <li><%= link_to "Regresar",teacher_dashboard_grades_filters_path(params[:branch_id],params[:group_id],params[:sprint_id],params[:lesson_id],params[:page_id]), :class => "active" %></li>
    </ol>
    <section class="grades-input">
      <div class="header">
        <h4><%= @sprint.name %></h4>
        <h4><%= @softskill %></h4>
        <h4><%= @group.name %></h4>
      </div>
      <%= simple_form_for :input, url: teacher_grades_softskill_input_path do |f| %>
        <%= f.input :sprint_id,as: :hidden, :input_html => {:value => params[:sprint_id]} %>
        <%= f.input :group_id,as: :hidden, :input_html => {:value => params[:group_id]} %>
        <%= f.input :stype,as: :hidden, :input_html => {:value => params[:stype]} %>
        <table class="table table-bordered table-condensed">
        <tr>
          <th>Estudiante</th>
          <% @soft_skills.each do |sk| %>
            <th><%= sk["name"] %><br />(Nota máx. <%= sk["points"] %>)</th>
          <% end %>
        </tr>
        <% @users.each do |user| %>
          <tr>
            <td>
              <%= image_tag user.avatar(:student_dashboard), :class => "user-image" if user.avatar.exists? %>
              <h4 class="mt-0"><%= user.profile.name %></h4>
              <p><%= user.code %></p>
              <%= f.input :users,as: :hidden, :input_html => {:name => "input[users][]", :value => user.id} %>
            </td>
            <% @soft_skills.each do |sk| %>
              <% user_points = find_soft_skills_submissions_points(user.id,sk["id"],@submissions) %>
              <td style="vertical-align:middle;">
                <%= f.input :grades, label:false,
                            :input_html => {:type => "number",:name => "input[grades][#{sk["id"]}][]",
                                            :step => "0.1", :value => (!user_points.nil? ? user_points.round(2) : nil)} %>
              </td>
            <% end %>
          </tr>
        <% end %>
        <tr>
          <td></td>
          <td colspan="<%= @soft_skills.size %>" style="text-align:right;">
            <%= f.submit "Guardar Cambios", class: "btn btn-primary" %>
          </td>
        </tr>
        </table>
      <% end %>
    </section>
</div>

app/views/teacher/dashboard/recomendations.html.erb
<h1>Teacher::Dashboard#recomendations</h1>
<p>Find me in app/views/teacher/dashboard/recomendations.html.erb</p>

app/views/teacher/dashboard/sprints.html.erb
<h1>Teacher::Dashboard#sprints</h1>
<p>Find me in app/views/teacher/dashboard/sprints.html.erb</p>

app/views/teacher/dashboard/students.html.erb
<h1>Teacher::Dashboard#students</h1>
<p>Find me in app/views/teacher/dashboard/students.html.erb</p>

app/views/teacher/dashboard/teacher_stats.html.erb
<h1>Teacher::Dashboard#teacher_stats</h1>
<p>Find me in app/views/teacher/dashboard/teacher_stats.html.erb</p>